apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: k8sazurev1maxrecplicacount
spec:
  applyTo:
    - groups: ["apps"]
      kinds: ["Deployment"]
      versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
  location: "spec.replicas"
  parameters:
    pathTests:
      - subPath: "spec.replicas"
        condition: MustExist
    assign:
      value: 1
